<?php
$subject = array(
			'7th'=>array(
										'BASIC MATHEMATICS',
										'ENGLISH',
										'ENGINEERING PHYSICS(GROUP-1)',
										'BASIC ENGINEERING DRAWING',
										'APPLIED MECHANICS',
										'ENGINEERING WORKSHOP PRACTICE'			
							),

			'biomedical'=>array(
							'1'=>array(
										'BASIC MATHEMATICS',
										'ENGLISH',
										'ENGINEERING CHEMISTRY (GROUP-2)',
										'ELECTRONIC COMPONENTS & PRACTICE',
										'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
										'BASIC OF COMPUTER & INFORMATION TECHNOLOGY'
										),
							'2'=>array(
										'CONTRIBUTOR PERSONALITY DEVELOPMENET',
										'ADVANCED MATHEMATICS (GROUP-1)',
										'BASIC PHYSICS (GROUP-2)',
										'FUNDAMENTAL OF DIGITAL ELECTRONICS',
										'HUMAN ANATOMY',
										'HUMAN PHYSIOLOGY'
										),
							'3'=>array(
										'HUMAN RESOURCE MANAGEMENT',
										'BASIC ELECTRONICS',
										'DATA COMMUNICATION & NETWORKING',
										'MEDICAL ELECTRONICS',
										'MEDICAL SENSORS & MEASUREMENT TECHNIQUE'
										),
							'4'=>array(
										'ENTREPRENEURSHIP DEVELOPMENT',
										'MICROPROCESSOR AND ASSEMBLY LANGUAGE PROGRAMMING',
										'HOSPITAL MANAGEMENT & INFORMATION SYSTEM',
										'DIAGNOSTIC MEDICAL INSTRUMENTATION',
										'ANALYTICAL AND OPTICAL INSTRUMENTATION',
										'SEMINAR'
										),
							'5'=>array(
										'MI MICRO-CONTROLLER APPLICATION IN MEDICAL TECHNOLOGY',
										'MEDICAL IMAGING TECHNIQUES'.
										'CRITICAL CARE INSTRUMENTATION',
										'THERAPEUTIC MEDICAL INSTRUMENTATION',
										'PROJECT-I'
										),
							'6'=>array(
										'BIO-MEDICAL DIGITAL SIGNAL PROCESSING',
										'REHABILITATION ENGINEERING',
										'TELEMEDICAL INSTRUMENTATION',
										'OPTHALMIC INSTRUMENTATION',
										'VIRTUAL MEDICAL INSTRUMENTATIO',
										'BIO MATERIALS AND IMPLANTS',
										'PROJECT-II'
										),
							),

			'civil'=>array(
							'1'=>array(
										'BASIC MATHEMATICS',
										'ENGLISH',
										'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
										'ENGINEERING PHYSICS (GROUP-1)',
										'BASIC ENGINEERING DRAWING',
										'COMPUTER APPLICATION & GRAPHICS'
										),
							'2'=>array(
										'CONTRIBUTOR PERSONALITY DEVELOPMENT',
										'ADVANCED MATHEMATICS (GROUP-2)',
										'APPLIED MECHANICS',
										'APPLIED CHEMISTRY (GROUP-1)',
										'BUILDING DRAWING',
										'BASIC MECHANICAL ENGINEERING',
										'CIVIL ENGINEERING WORKSHOP PRACTICE'
										),
							'3'=>array(
										'BUILDING MATERIALS',
										'CONSTRUCTION TECHNOLOGY',
										'HYDRAULICS',
										'STRUCTURAL MECHANICS',
										'SURVEYING'
										),
							'4'=>array(
										'STRUCTURAL MECHANICS-II',
										'ADVANCED SURVEYING',
										'BASIC TRANSPORTATION ENGINEERING',
										'WATER RESOURCES MANAGEMENT',
										'SOIL MECHANICS',
										'COMPUTER AIDED DRAWING'
										),
							'5'=>array(
										'DESIGN OF STEEL STRUCTURE',
										'CONCRETE TECHNOLOGY',
										'WATER SUPPLY & SANITARY ENGGINEERING',
										'ESTIMATING , COSTING & VALUATION',
										'ADVANCE CONSTRUCTION TECHNOLOGY',
										'HIGHWAY ENGINEERING',
										'IRRIGATION ENGINEERING',
										'ENVIRONMENTAL ENGINEERING &POLLUTION CONTROL',
										'PROJECT-I'
										),
							'6'=>array(
										'DESIGN OF REINFORCED CONCRETE STRUCTURES',
										'CONSTRUCTION QUALITY CONTROL & MONITORING',
										'CONSTRUCTION PROJECT MANAGEMNET',
										'BUILDING SERVICES',
										'MAINTANANCE & REHABILATION OF STRUCTURES',
										'RAILWAY , HARBOUR & TUNNEL ENGINEERING',
										'TRAFFIC ENGINEERING',
										'PAVEMENT DESIGN',
										'GROUND WATER ENGINEERING',
										'ADVANCE HYDROLOGY',
										'SOLID WASTE MANAGEMENT',
										'WATER AND WASTE WATER MANAGEMENT',
										'PROJECT-II'
										),
							),

			'6th'=>array(
							
										'BASIC MATHEMATICS',
										'English',
										'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
										'COMPUTER PROGRAMMING',
										'FUNDAMENTAL OF DIGITAL ELECTRONIC',
										'FUNDAMENTAL OF COMPUTER APPLICATION'
									
							),

			'electrical'=>array(
								'1'=>array(
											'BASIC MATHEMATICS',
											'ENGLISH',
											'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
											'ENGINEERING CHEMISTRY ( GROUP-2 )',
											'BASIC OF COMPUTER & INFORMATION TECHNOLOGY',
											'FUNDAMENTAL OF MECHANICAL ENGINEERING'
											),
								'2'=>array(
											'CONTRIBUTOR PERSONALITY DEVELOPMENET',
											'ADVANCED MATHEMATICS (GROUP-1)',
											'BASIC OF CIVIL ENGINEERING',
											'BASIC PHYSICS (GROUP-2)',
											'BASIC ENGINEERING DRAWING',
											'D.C.CIRCUITS',
											'ELECTRICAL ENGINEERING WORKSHOP PRACTICE'
											),
								'3'=>array(
											'AC CIRCUITS',
											'D C MACHINES AND TRANSFORMER',
											'ELECTRICAL INSTRUMENTION',
											'ELECTRICAL POWER GENERATION',
											'ELECTRONICS COMPONENTS AND CIRCUITS'
											),
								'4'=>array(
											'POLYPHASE TRANSFORMERS AND ROTATING AC MACHINES',
											'TRANSMISSION AND DISTRIBUTION OF ELECTRICAL POWER',
											'UTILIZATION OF ELECTRICAL ENERGY',
											'DIGITAL ELECTRONICS AND DIGITAL INSTRUMENTS',
											'COMPUTER AIDED ELECTRICAL DRAWING AND SIMULATION'
											),
								'5'=>array(
											'WIRING ESTIMATING, COSTING & CONTRACTING',
											'ENERGY CONSERVATION & AUDIT',
											'POWER ELECTRONICS',
											'MICROPROCESSOR AND CONTROLLER APPLICATIONS',
											'WIND AND SOLAR ENERGY SYSTEMS',
											'SPECIAL ELECTRICAL MACHINES',
											'ELECTRIC TRACTION AND CONTROL',
											'PROJECT-I'
											),
								'6'=>array(
											'SWITCHGEAR & PROTECTION',
											'INSTALLATION, COMMISSIONING AND MAINTENANCE',
											'POWER SYSTEM OPERATION AND CONTROL',
											'SUBSTATION ENGINNERING AND POWER QUALITY',
											'SOLAR AND WIND SYSTEM',
											'DESIGN PARAMETERS OF ELECTRICAL EQUIPEMENT AND MACHINES',
											'ELECTRICAL DRIVES',
											'SPECIAL ELECTRICAL MACHINES',
											'MAINTENANCE OF TRANSFORMER AND CIRCUIT BREAKER',
											'ELECTRICAL TRACTION AND CONTROL',
											'ELECTRIFICATION OF BUILDING COMPLEXES',
											'PROJECT-II'
											),
								),

			'ec'=>array(
						'1'=>array(
									'BASIC MATHEMATICS',
									'ENGLISH',
									'BASIC PHYSICS(GROUP-2)',
									'ELECTRONIC COMPONENTS & PRACTICE',
									'BASIC OF ELECTRICAL ENGINEERING',
									'BASIC OF COMPUTER & INFORMATION TECHNOLOGY'
									),
						'2'=>array(
									'CONTRIBUTOR PERSONALITY DEVELOPMENET',
									'ADVANCED MATHEMATICS (GROUP-1)',
									'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
									'ELECTRONIC CIRCUITS & APPLICATIONS',
									'ELECTRONIC NETWORKS',
									'ELECTRONICS WORKSHOP'
									),
						'3'=>array(
									'ANTENNA & WAVE PROPAGATION',
									'ANALOG ELECTRONICS',
									'PRINCIPLE OF ELECTRONIC COMMUNICATION',
									'DIGITAL LOGIC DESIGN',
									'PROGRAMMING IN C'
									),
						'4'=>array(
									'MICROPROCESSOR AND ASSEMBLY LANGUAGE PROGRAMMING',
									'DIGITAL COMMUNICATION',
									'OPTICAL COMMUNICATION',
									'ELECTRONICS INSTRUMENTS AND MEASUREMENT',
									'INDUSTRIAL ELECTRONICS',
									'CIRCUIT DESIGN TOOLS'
									),
						'5'=>array(
									'MICROCONTROLLER',
									'MOBILE COMMUNICATION',
									'MICROWAVE & RADAR ENGINEERING',
									'SOFTWARE PRACTICES',
									'COMPUTER NETWORKS',
									'INSTRUMENTATION & CONTROL ENGG',
									'PROJECT-I'
									),
						'6'=>array(
									'ENTERPRENURSHIP AND INDUSTRIAL MANAGEMENT',
									'CONSUMER ELECTRONICS',
									'MAINTENANCE OF ELECTRONICS EQUIPMENTS',
									'VLSI',
									'EMBEDED SYSTEM',
									'MULTIMEDIA COMMUNICATION',
									'INDUSTRIAL AUTOMATION',
									'ROBOTICS & AUTOTRONICS',
									'PROJECT - II'
									),
						),

			'it'=>array(
						'1'=>array(
									'BASIC MATHEMATICS',
									'ENGLISH',
									'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
									'COMPUTER PROGRAMMING',
									'FUNDAMENTAL OF DIGITAL ELECTRONIC',
									'FUNDAMENTAL OF COMPUTER APPLICATION'
									),
						'2'=>array(
									'CONTRIBUTOR PERSONALITY DEVELOPMENET',
									'ADVANCED MATHEMATICS(GROUP-1)',
									'BASIC PHYSICS (GROUP-2)',
									'BASIC ELECTRONICS',
									'ADVANCED COMPUTER PROGRAMMING',
									'FUNDAMENTAL OF INFORMATION TECHNOLGY'
									),
						'3'=>array(
									'DIGITAL MEMORY SYSTEM',
									'OPERATING SYSTEM',
									'COMPUTER GRAPHICS',
									'DATA STRUCTURE',
									'SOFTWARE PRACTICES WITH VB.NET'
									),
						'4'=>array(
									'INFORMATION COMMUNICATION TECHNOLOGY',
									'OBJECT ORINTED PROGRAMMING',
									'FUNDAMENTALS OF SOFTWARE DEVELOPMENT',
									'INTERNET TECHNOLOGY',
									'DATABASE MANAGEMENT'
									),
						'5'=>array(
									'JAVA PROGRAMMING',
									'INFORMATION COMMUNICATION NETWORKS',
									'ESSENTIALS OF NETWORK SECURITY',
									'WEB PROGRAMMING USING ASP.NET',
									'MANAGEMENT INFORMATION SYSTEM',
									'PROJECT - I'
									),
						'6'=>array(
									'WEB AND NETWORK SECURITY',
									'ADVANCE JAVA PROGRAMMING',
									'ANDROID APPS DEVELOPMENT',
									'WEB DESIGNING USING PHP AND MYSQL',
									'DATA MINING AND WAREHOUSING',
									'DATABASE ADMINISTRATION',
									'PROJECT-II'
									),
						),

			'ic'=>array(
						'1'=>array(
									'BASIC MATHEMATICS',
									'ENGLISH',
									'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
									'BASIC INSTRUMENTATION',
									'INSTRUMENTATION WORKSHOP',
									'PRINCIPLES OF CHEMICAL ENGINEERING'
									),
						'2'=>array(
									'CONTRIBUTOR PERSONALITY DEVELOPMENET',
									'BASIC PHYSICS (GROUP-2)',
									'INDUSTRIAL TRANSDUCERS',
									'INSTRUMENTATION DEVICE MATERIALS',
									'INSTRUMENTATION DEVICES & COMPONENTS',
									'INSTRUMENT CONFIGURATION PRATICES'
									),
						'3'=>array(
									'SAFETY INSTRUMENTED SYSTEMS & SAFETY INTEGRATED LEVEL',
									'TELEMETRY SYSTEM',
									'DIGITAL TECHNIQUES',
									'CONTROL COMPONENTS',
									'PROCESS APPLICATION & INSTRUMENTATION MAINTENANCE MANAGEMENT',
									'INSTRUMENTATION DRAWING'
									),
						'4'=>array(
									'CONTROL INSTRUMENTATION SYSTEM',
									'PROGRAMMABLE LOGIC CONTROLLER AND DISTRIBUTED CONTROL SYSTEM',
									'PROCESS INSTRUMENTATION-I',
									'BIOMEDICAL INSTRUMENTATION',
									'INSTRUMENTATION SIMULATION PRACTICES'
									),
						'5'=>array(
									'ELECTRONIC & PNEUMATIC INSTRUMENTATION',
									'PROCESS INSTRUMENTATION-II',
									'ANALYTICAL INSTRUMENTATION',
									'PLC PROGRAMMING',
									'MICROPROCESSOR AND MICROCONTROLLER IN INSTRUMENATION',
									'PROJECT-I(WITH SEMINAR)'
									),
						'6'=>array(
									'APPLIED INSTRUMENTATION',
									'INDUSTRIAL POWER CONTROL',
									'DCS AND SCADA',
									'INSTRUMENTATION DATA COMMUNICATION',
									'PIC MICROCONTROLLER AND EMBEDED SYSTEMS',
									'EMBEDED NETWORKS',
									'PROJECT- II ( WITH SEMINAR)'
									),
						),

			'mechanical'=>array(
							'1'=>array(
										'BASIC MATHEMATICS',
										'ENGLISH',
										'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
										'ENGINEERING PHYSICS (GROUP-1)',
										'BASIC ENGINEERING DRAWING',
										'ENGINEERING WORKSHOP PRACTICE'
										),
							'2'=>array(
										'CONTRIBUTOR PERSONALITY DEVELOPMENET',
										'ADVANCED MATHEMATICS (GROUP-2)',
										'APPLIED MECHANICS',
										'MATERIAL SCIENCE & METALLURGY',
										'MECHANICAL DRAFTING',
										'BASIC OF CIVIL ENGINEERING'
										),
							'3'=>array(
										'MANUFACTURING ENGINEERING-I',
										'THERMODYNAMICS',
										'FLUID MECHANICS AND HYDRAULIC MACHINES',
										'STRENGTH OF MATERIALS',
										'APPLIED ELECTRICAL AND ELECTRONIC ENGINEERING',
										'COMPUTER AIDED MACHINE DRAWING',
										'HUMAN RESOURCE MANAGEMENT'
										),
							'4'=>array(
										'MANUFACTURING ENGINEERING - II',
										'THERMAL ENGINEERING-I',
										'THEORY OF MACHINES',
										'COMPUTER AIDED DESIGN',
										'METROLOGY & INSTRUMENTATION',
										'PLANT MAINTENANCE AND SAFETY'
										),
							'5'=>array(
										'THERMAL ENGINEERING-II',
										'DESIGN OF MACHINE ELEMENTS',
										'MANUFACTURING ENGINEERING-III',
										'INDUSTRIAL ENGINEERING',
										'ESTIMATING, COSTING AND ENGINEERING CONTRACTING',
										'SELF EMPLOYEMENT AND ENTREPRENEURSHIP DEVELOPMENT (MANUFACTURING ENGINEERING)',
										'OPERATIONS MANAGEMENT AND INFORMATION SYSTEMS (MANUFACTURING ENGINEERING)',
										'SELF EMPLOYEMENT AND ENTREPRENEURSHIP DEVELOPMENT (THERMAL ENGINEERING)',
										'OPERATIONS MANAGEMENT AND INFORMATION SYSTEMS (THERMAL ENGINEERING)',
										'SELF EMPLOYEMENT AND ENTREPRENEURSHIP DEVELOPMENT (FLUID ENGINEERING)',
										'OPERATIONS MANAGEMENT AND INFORMATION SYSTEMS (FLUID ENGINEERING)',			
										'PROJECT-I'
										),
							'6'=>array(
										'COMPUTER AIDED MANUFACTURING',
										'TOOL ENGINEERING',
										'INDUSTRIAL MANAGEMENT',
										'MANUFACTURING SYSTEMS',
										'FABRICATION TECHNOLOGY',
										'POWER PLANT ENGINEERING',
										'THERMAL SYSTEMS AND ENERGY EFFICIENCY',
										'HYDRAULIC SYSTEMS',
										'PNEUMATIC SYSTEMS',
										'PROJECT-II'
										),
							),

			'plastic'=>array(
							'1'=>array(
										'BASIC MATHEMATICS',
										'ENGLISH',
										'ENGINEERING PHYSICS (GROUP-1)',
										'FUNDAMENTAL OF MECHANICAL ENGINEERING',
										'BASIC POLYMER CHEMISTRY',
										'COMPUTER APPLICATION & GRAPHICS'
										),
							'2'=>array(
										'CONTRIBUTOR PERSONALITY DEVELOPMENET',
										'ENVIRONMENT CONSERVATION & HAZARD MANAGEMENT',
										'BASIC ENGINEERING DRAWING',
										'BASIC OF ELECTRICAL ENGINEERING',
										'POLYMER CHEMISTRY',
										'PLASTIC ENGINEERING WORKSHOP'
										),
							'3'=>array(
										'HUMAN RESOURSE MANAGEMENT',
										'BASIC MOULD DESIGN',
										'COMPRESSION TRANSFER & INJECTION MOULDING OF THERMOSE',
										'MOULD FABRICATION TECHNOLOGY-I',
										'PLASTIC MATERIALS-I',
										'TECHNOLOGY FOR INJECTION MOULDING'
										),
							'4'=>array(
										'ENTREPRENEURSHIP DEVELOPMENT',
										'BLOW ROTATIONAL AND THERMOFORMING PROCESS',
										'DESIGN FOR INJECTION MOULD',
										'HYDRAULIC & PNEUMATIC SYSTEMS',
										'PLASTICS EXTRUSION TECHNOLOGY',
										'PROCESS INSTRUMENTATION AND MAINTENANCE (PIM)'
										),
							'5'=>array(
										'INDUSTRIAL TRAINING-I'
										),
							'6'=>array(
										'INDUSTRIAL MANAGEMENT',
										'DESIGN FOR BLOW AND THERMOFORMING MOULDS',
										'MOULD FABRICATION TECHNOLOGY-II',
										'PLASTIC MATERIALS-II',
										'PLASTICS TESTING AND QUALITY MANAGEMENT',
										'SECONDARY PROCESSING TECHNIQUES'
										),
						),
);
